# Generated by Django 2.2 on 2019-10-31 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=244, null=True)),
                ('gender', models.CharField(blank=True, max_length=244, null=True)),
                ('profession', models.CharField(blank=True, max_length=244, null=True)),
                ('blood', models.CharField(blank=True, max_length=244, null=True)),
                ('cell', models.CharField(blank=True, max_length=244, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
