# Generated by Django 2.2 on 2019-11-20 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-time',)},
        ),
    ]
