# Generated by Django 2.2 on 2019-11-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20191120_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, default='default.png', upload_to='profile_pics'),
        ),
    ]
