# Generated by Django 2.2 on 2019-11-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='img',
            field=models.CharField(blank=True, max_length=244, null=True),
        ),
    ]
