# Generated by Django 2.2 on 2019-11-23 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20191124_0429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='img',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='comment',
            name='person',
            field=models.ManyToManyField(to='main.Profile'),
        ),
    ]
