# Generated by Django 2.2 on 2019-11-23 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_comment_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='person',
            field=models.ManyToManyField(to='main.Profile'),
        ),
    ]
