# Generated by Django 2.2 on 2019-12-07 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_post_liked_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='liked_user',
        ),
    ]
